Repository UBC-MDS/Rmagine, pull requests merged in 2020-03, with the labels that each got.

#24 created tunnel filter in R
  R/fishbowl_filter.R
  R/tunnel_filter.R
  tests/testthat/test_tunnel.R
Labels: individual

#27 added colour_filters function and test file
  R/colour_filters.R
  tests/testthat/test_colourfilter.R
Labels: individual

#28 updated README with usage instructions and package dependencies
  README.Rmd
  README.md
Labels: documentation

#35 Added package import for pipe operator in docstring
  DESCRIPTION
  NAMESPACE
  R/colour_filters.R
  tests/testthat/test_colourfilter.R
Labels: bug

#51 Added Rmd check and codecov badges
  README.Rmd
  README.md
Labels: documentation
